name: "Setup reviewdog"
description: "🐶 This action sets up reviewdog"
inputs:
  reviewdog_version:
    description: "reviewdog version. [latest,nightly,vX.Y.Z]"
    default: "latest"
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/install.sh
      shell: sh
      env:
        REVIEWDOG_VERSION: ${{ inputs.reviewdog_version }}
        REVIEWDOG_TEMPDIR: ${{ runner.temp }}
    - run: |
        if ! command -v reviewdog >/dev/null 2>&1; then
          echo "reviewdog was not installed"
          exit 1
        fi
        echo "::group::📖 reviewdog -h"
        reviewdog -h 2>&1 || true
        echo "::endgroup::"
      shell: sh

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: "terminal"
  color: "gray-dark"
